################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../src/model/compute_sub_0000.c \
../src/model/compute_sub_0001.c \
../src/model/compute_sub_0002.c \
../src/model/compute_sub_0003.c \
../src/model/compute_sub_0004.c \
../src/model/compute_sub_0005.c \
../src/model/compute_sub_0006.c \
../src/model/compute_sub_0007.c \
../src/model/compute_sub_0008.c \
../src/model/compute_sub_0009.c \
../src/model/compute_sub_0010.c \
../src/model/compute_sub_0011.c \
../src/model/compute_sub_0012.c \
../src/model/compute_sub_0013.c \
../src/model/compute_sub_0014.c \
../src/model/compute_sub_0015.c \
../src/model/compute_sub_0016.c \
../src/model/compute_sub_0017.c \
../src/model/compute_sub_0018.c \
../src/model/compute_sub_0019.c \
../src/model/compute_sub_0020.c \
../src/model/compute_sub_0021.c \
../src/model/compute_sub_0022.c \
../src/model/compute_sub_0023.c \
../src/model/compute_sub_0024.c \
../src/model/compute_sub_0025.c \
../src/model/compute_sub_0026.c \
../src/model/compute_sub_0027.c \
../src/model/compute_sub_0028.c \
../src/model/compute_sub_0029.c \
../src/model/compute_sub_0030.c \
../src/model/compute_sub_0031.c \
../src/model/compute_sub_0033.c \
../src/model/kernel_library_int.c \
../src/model/kernel_library_utils.c \
../src/model/model.c \
../src/model/model_io_data.c \
../src/model/sub_0000_command_stream.c \
../src/model/sub_0000_invoke.c \
../src/model/sub_0000_io_data.c \
../src/model/sub_0000_model_data.c \
../src/model/sub_0000_tensors.c \
../src/model/sub_0001_command_stream.c \
../src/model/sub_0001_invoke.c \
../src/model/sub_0001_model_data.c \
../src/model/sub_0001_tensors.c \
../src/model/sub_0002_command_stream.c \
../src/model/sub_0002_invoke.c \
../src/model/sub_0002_io_data.c \
../src/model/sub_0002_model_data.c \
../src/model/sub_0002_tensors.c \
../src/model/sub_0003_command_stream.c \
../src/model/sub_0003_invoke.c \
../src/model/sub_0003_model_data.c \
../src/model/sub_0003_tensors.c \
../src/model/sub_0004_command_stream.c \
../src/model/sub_0004_invoke.c \
../src/model/sub_0004_io_data.c \
../src/model/sub_0004_model_data.c \
../src/model/sub_0004_tensors.c \
../src/model/sub_0005_command_stream.c \
../src/model/sub_0005_invoke.c \
../src/model/sub_0005_model_data.c \
../src/model/sub_0005_tensors.c \
../src/model/sub_0006_command_stream.c \
../src/model/sub_0006_invoke.c \
../src/model/sub_0006_io_data.c \
../src/model/sub_0006_model_data.c \
../src/model/sub_0006_tensors.c \
../src/model/sub_0007_command_stream.c \
../src/model/sub_0007_invoke.c \
../src/model/sub_0007_model_data.c \
../src/model/sub_0007_tensors.c \
../src/model/sub_0008_command_stream.c \
../src/model/sub_0008_invoke.c \
../src/model/sub_0008_io_data.c \
../src/model/sub_0008_model_data.c \
../src/model/sub_0008_tensors.c \
../src/model/sub_0009_command_stream.c \
../src/model/sub_0009_invoke.c \
../src/model/sub_0009_model_data.c \
../src/model/sub_0009_tensors.c \
../src/model/sub_0010_command_stream.c \
../src/model/sub_0010_invoke.c \
../src/model/sub_0010_io_data.c \
../src/model/sub_0010_model_data.c \
../src/model/sub_0010_tensors.c \
../src/model/sub_0011_command_stream.c \
../src/model/sub_0011_invoke.c \
../src/model/sub_0011_model_data.c \
../src/model/sub_0011_tensors.c \
../src/model/sub_0012_command_stream.c \
../src/model/sub_0012_invoke.c \
../src/model/sub_0012_io_data.c \
../src/model/sub_0012_model_data.c \
../src/model/sub_0012_tensors.c \
../src/model/sub_0013_command_stream.c \
../src/model/sub_0013_invoke.c \
../src/model/sub_0013_model_data.c \
../src/model/sub_0013_tensors.c \
../src/model/sub_0014_command_stream.c \
../src/model/sub_0014_invoke.c \
../src/model/sub_0014_io_data.c \
../src/model/sub_0014_model_data.c \
../src/model/sub_0014_tensors.c \
../src/model/sub_0015_command_stream.c \
../src/model/sub_0015_invoke.c \
../src/model/sub_0015_model_data.c \
../src/model/sub_0015_tensors.c \
../src/model/sub_0016_command_stream.c \
../src/model/sub_0016_invoke.c \
../src/model/sub_0016_io_data.c \
../src/model/sub_0016_model_data.c \
../src/model/sub_0016_tensors.c \
../src/model/sub_0017_command_stream.c \
../src/model/sub_0017_invoke.c \
../src/model/sub_0017_model_data.c \
../src/model/sub_0017_tensors.c \
../src/model/sub_0018_command_stream.c \
../src/model/sub_0018_invoke.c \
../src/model/sub_0018_io_data.c \
../src/model/sub_0018_model_data.c \
../src/model/sub_0018_tensors.c \
../src/model/sub_0019_command_stream.c \
../src/model/sub_0019_invoke.c \
../src/model/sub_0019_model_data.c \
../src/model/sub_0019_tensors.c \
../src/model/sub_0020_command_stream.c \
../src/model/sub_0020_invoke.c \
../src/model/sub_0020_io_data.c \
../src/model/sub_0020_model_data.c \
../src/model/sub_0020_tensors.c \
../src/model/sub_0021_command_stream.c \
../src/model/sub_0021_invoke.c \
../src/model/sub_0021_model_data.c \
../src/model/sub_0021_tensors.c \
../src/model/sub_0022_command_stream.c \
../src/model/sub_0022_invoke.c \
../src/model/sub_0022_io_data.c \
../src/model/sub_0022_model_data.c \
../src/model/sub_0022_tensors.c \
../src/model/sub_0023_command_stream.c \
../src/model/sub_0023_invoke.c \
../src/model/sub_0023_model_data.c \
../src/model/sub_0023_tensors.c \
../src/model/sub_0024_command_stream.c \
../src/model/sub_0024_invoke.c \
../src/model/sub_0024_io_data.c \
../src/model/sub_0024_model_data.c \
../src/model/sub_0024_tensors.c \
../src/model/sub_0025_command_stream.c \
../src/model/sub_0025_invoke.c \
../src/model/sub_0025_model_data.c \
../src/model/sub_0025_tensors.c \
../src/model/sub_0026_command_stream.c \
../src/model/sub_0026_invoke.c \
../src/model/sub_0026_io_data.c \
../src/model/sub_0026_model_data.c \
../src/model/sub_0026_tensors.c \
../src/model/sub_0027_command_stream.c \
../src/model/sub_0027_invoke.c \
../src/model/sub_0027_model_data.c \
../src/model/sub_0027_tensors.c \
../src/model/sub_0028_command_stream.c \
../src/model/sub_0028_invoke.c \
../src/model/sub_0028_io_data.c \
../src/model/sub_0028_model_data.c \
../src/model/sub_0028_tensors.c \
../src/model/sub_0029_command_stream.c \
../src/model/sub_0029_invoke.c \
../src/model/sub_0029_model_data.c \
../src/model/sub_0029_tensors.c \
../src/model/sub_0030_command_stream.c \
../src/model/sub_0030_invoke.c \
../src/model/sub_0030_io_data.c \
../src/model/sub_0030_model_data.c \
../src/model/sub_0030_tensors.c \
../src/model/sub_0032_command_stream.c \
../src/model/sub_0032_invoke.c \
../src/model/sub_0032_io_data.c \
../src/model/sub_0032_model_data.c \
../src/model/sub_0032_tensors.c 

C_DEPS += \
./src/model/compute_sub_0000.d \
./src/model/compute_sub_0001.d \
./src/model/compute_sub_0002.d \
./src/model/compute_sub_0003.d \
./src/model/compute_sub_0004.d \
./src/model/compute_sub_0005.d \
./src/model/compute_sub_0006.d \
./src/model/compute_sub_0007.d \
./src/model/compute_sub_0008.d \
./src/model/compute_sub_0009.d \
./src/model/compute_sub_0010.d \
./src/model/compute_sub_0011.d \
./src/model/compute_sub_0012.d \
./src/model/compute_sub_0013.d \
./src/model/compute_sub_0014.d \
./src/model/compute_sub_0015.d \
./src/model/compute_sub_0016.d \
./src/model/compute_sub_0017.d \
./src/model/compute_sub_0018.d \
./src/model/compute_sub_0019.d \
./src/model/compute_sub_0020.d \
./src/model/compute_sub_0021.d \
./src/model/compute_sub_0022.d \
./src/model/compute_sub_0023.d \
./src/model/compute_sub_0024.d \
./src/model/compute_sub_0025.d \
./src/model/compute_sub_0026.d \
./src/model/compute_sub_0027.d \
./src/model/compute_sub_0028.d \
./src/model/compute_sub_0029.d \
./src/model/compute_sub_0030.d \
./src/model/compute_sub_0031.d \
./src/model/compute_sub_0033.d \
./src/model/kernel_library_int.d \
./src/model/kernel_library_utils.d \
./src/model/model.d \
./src/model/model_io_data.d \
./src/model/sub_0000_command_stream.d \
./src/model/sub_0000_invoke.d \
./src/model/sub_0000_io_data.d \
./src/model/sub_0000_model_data.d \
./src/model/sub_0000_tensors.d \
./src/model/sub_0001_command_stream.d \
./src/model/sub_0001_invoke.d \
./src/model/sub_0001_model_data.d \
./src/model/sub_0001_tensors.d \
./src/model/sub_0002_command_stream.d \
./src/model/sub_0002_invoke.d \
./src/model/sub_0002_io_data.d \
./src/model/sub_0002_model_data.d \
./src/model/sub_0002_tensors.d \
./src/model/sub_0003_command_stream.d \
./src/model/sub_0003_invoke.d \
./src/model/sub_0003_model_data.d \
./src/model/sub_0003_tensors.d \
./src/model/sub_0004_command_stream.d \
./src/model/sub_0004_invoke.d \
./src/model/sub_0004_io_data.d \
./src/model/sub_0004_model_data.d \
./src/model/sub_0004_tensors.d \
./src/model/sub_0005_command_stream.d \
./src/model/sub_0005_invoke.d \
./src/model/sub_0005_model_data.d \
./src/model/sub_0005_tensors.d \
./src/model/sub_0006_command_stream.d \
./src/model/sub_0006_invoke.d \
./src/model/sub_0006_io_data.d \
./src/model/sub_0006_model_data.d \
./src/model/sub_0006_tensors.d \
./src/model/sub_0007_command_stream.d \
./src/model/sub_0007_invoke.d \
./src/model/sub_0007_model_data.d \
./src/model/sub_0007_tensors.d \
./src/model/sub_0008_command_stream.d \
./src/model/sub_0008_invoke.d \
./src/model/sub_0008_io_data.d \
./src/model/sub_0008_model_data.d \
./src/model/sub_0008_tensors.d \
./src/model/sub_0009_command_stream.d \
./src/model/sub_0009_invoke.d \
./src/model/sub_0009_model_data.d \
./src/model/sub_0009_tensors.d \
./src/model/sub_0010_command_stream.d \
./src/model/sub_0010_invoke.d \
./src/model/sub_0010_io_data.d \
./src/model/sub_0010_model_data.d \
./src/model/sub_0010_tensors.d \
./src/model/sub_0011_command_stream.d \
./src/model/sub_0011_invoke.d \
./src/model/sub_0011_model_data.d \
./src/model/sub_0011_tensors.d \
./src/model/sub_0012_command_stream.d \
./src/model/sub_0012_invoke.d \
./src/model/sub_0012_io_data.d \
./src/model/sub_0012_model_data.d \
./src/model/sub_0012_tensors.d \
./src/model/sub_0013_command_stream.d \
./src/model/sub_0013_invoke.d \
./src/model/sub_0013_model_data.d \
./src/model/sub_0013_tensors.d \
./src/model/sub_0014_command_stream.d \
./src/model/sub_0014_invoke.d \
./src/model/sub_0014_io_data.d \
./src/model/sub_0014_model_data.d \
./src/model/sub_0014_tensors.d \
./src/model/sub_0015_command_stream.d \
./src/model/sub_0015_invoke.d \
./src/model/sub_0015_model_data.d \
./src/model/sub_0015_tensors.d \
./src/model/sub_0016_command_stream.d \
./src/model/sub_0016_invoke.d \
./src/model/sub_0016_io_data.d \
./src/model/sub_0016_model_data.d \
./src/model/sub_0016_tensors.d \
./src/model/sub_0017_command_stream.d \
./src/model/sub_0017_invoke.d \
./src/model/sub_0017_model_data.d \
./src/model/sub_0017_tensors.d \
./src/model/sub_0018_command_stream.d \
./src/model/sub_0018_invoke.d \
./src/model/sub_0018_io_data.d \
./src/model/sub_0018_model_data.d \
./src/model/sub_0018_tensors.d \
./src/model/sub_0019_command_stream.d \
./src/model/sub_0019_invoke.d \
./src/model/sub_0019_model_data.d \
./src/model/sub_0019_tensors.d \
./src/model/sub_0020_command_stream.d \
./src/model/sub_0020_invoke.d \
./src/model/sub_0020_io_data.d \
./src/model/sub_0020_model_data.d \
./src/model/sub_0020_tensors.d \
./src/model/sub_0021_command_stream.d \
./src/model/sub_0021_invoke.d \
./src/model/sub_0021_model_data.d \
./src/model/sub_0021_tensors.d \
./src/model/sub_0022_command_stream.d \
./src/model/sub_0022_invoke.d \
./src/model/sub_0022_io_data.d \
./src/model/sub_0022_model_data.d \
./src/model/sub_0022_tensors.d \
./src/model/sub_0023_command_stream.d \
./src/model/sub_0023_invoke.d \
./src/model/sub_0023_model_data.d \
./src/model/sub_0023_tensors.d \
./src/model/sub_0024_command_stream.d \
./src/model/sub_0024_invoke.d \
./src/model/sub_0024_io_data.d \
./src/model/sub_0024_model_data.d \
./src/model/sub_0024_tensors.d \
./src/model/sub_0025_command_stream.d \
./src/model/sub_0025_invoke.d \
./src/model/sub_0025_model_data.d \
./src/model/sub_0025_tensors.d \
./src/model/sub_0026_command_stream.d \
./src/model/sub_0026_invoke.d \
./src/model/sub_0026_io_data.d \
./src/model/sub_0026_model_data.d \
./src/model/sub_0026_tensors.d \
./src/model/sub_0027_command_stream.d \
./src/model/sub_0027_invoke.d \
./src/model/sub_0027_model_data.d \
./src/model/sub_0027_tensors.d \
./src/model/sub_0028_command_stream.d \
./src/model/sub_0028_invoke.d \
./src/model/sub_0028_io_data.d \
./src/model/sub_0028_model_data.d \
./src/model/sub_0028_tensors.d \
./src/model/sub_0029_command_stream.d \
./src/model/sub_0029_invoke.d \
./src/model/sub_0029_model_data.d \
./src/model/sub_0029_tensors.d \
./src/model/sub_0030_command_stream.d \
./src/model/sub_0030_invoke.d \
./src/model/sub_0030_io_data.d \
./src/model/sub_0030_model_data.d \
./src/model/sub_0030_tensors.d \
./src/model/sub_0032_command_stream.d \
./src/model/sub_0032_invoke.d \
./src/model/sub_0032_io_data.d \
./src/model/sub_0032_model_data.d \
./src/model/sub_0032_tensors.d 

CREF += \
RA8P1_CAM_GLCDC_AI.cref 

OBJS += \
./src/model/compute_sub_0000.o \
./src/model/compute_sub_0001.o \
./src/model/compute_sub_0002.o \
./src/model/compute_sub_0003.o \
./src/model/compute_sub_0004.o \
./src/model/compute_sub_0005.o \
./src/model/compute_sub_0006.o \
./src/model/compute_sub_0007.o \
./src/model/compute_sub_0008.o \
./src/model/compute_sub_0009.o \
./src/model/compute_sub_0010.o \
./src/model/compute_sub_0011.o \
./src/model/compute_sub_0012.o \
./src/model/compute_sub_0013.o \
./src/model/compute_sub_0014.o \
./src/model/compute_sub_0015.o \
./src/model/compute_sub_0016.o \
./src/model/compute_sub_0017.o \
./src/model/compute_sub_0018.o \
./src/model/compute_sub_0019.o \
./src/model/compute_sub_0020.o \
./src/model/compute_sub_0021.o \
./src/model/compute_sub_0022.o \
./src/model/compute_sub_0023.o \
./src/model/compute_sub_0024.o \
./src/model/compute_sub_0025.o \
./src/model/compute_sub_0026.o \
./src/model/compute_sub_0027.o \
./src/model/compute_sub_0028.o \
./src/model/compute_sub_0029.o \
./src/model/compute_sub_0030.o \
./src/model/compute_sub_0031.o \
./src/model/compute_sub_0033.o \
./src/model/kernel_library_int.o \
./src/model/kernel_library_utils.o \
./src/model/model.o \
./src/model/model_io_data.o \
./src/model/sub_0000_command_stream.o \
./src/model/sub_0000_invoke.o \
./src/model/sub_0000_io_data.o \
./src/model/sub_0000_model_data.o \
./src/model/sub_0000_tensors.o \
./src/model/sub_0001_command_stream.o \
./src/model/sub_0001_invoke.o \
./src/model/sub_0001_model_data.o \
./src/model/sub_0001_tensors.o \
./src/model/sub_0002_command_stream.o \
./src/model/sub_0002_invoke.o \
./src/model/sub_0002_io_data.o \
./src/model/sub_0002_model_data.o \
./src/model/sub_0002_tensors.o \
./src/model/sub_0003_command_stream.o \
./src/model/sub_0003_invoke.o \
./src/model/sub_0003_model_data.o \
./src/model/sub_0003_tensors.o \
./src/model/sub_0004_command_stream.o \
./src/model/sub_0004_invoke.o \
./src/model/sub_0004_io_data.o \
./src/model/sub_0004_model_data.o \
./src/model/sub_0004_tensors.o \
./src/model/sub_0005_command_stream.o \
./src/model/sub_0005_invoke.o \
./src/model/sub_0005_model_data.o \
./src/model/sub_0005_tensors.o \
./src/model/sub_0006_command_stream.o \
./src/model/sub_0006_invoke.o \
./src/model/sub_0006_io_data.o \
./src/model/sub_0006_model_data.o \
./src/model/sub_0006_tensors.o \
./src/model/sub_0007_command_stream.o \
./src/model/sub_0007_invoke.o \
./src/model/sub_0007_model_data.o \
./src/model/sub_0007_tensors.o \
./src/model/sub_0008_command_stream.o \
./src/model/sub_0008_invoke.o \
./src/model/sub_0008_io_data.o \
./src/model/sub_0008_model_data.o \
./src/model/sub_0008_tensors.o \
./src/model/sub_0009_command_stream.o \
./src/model/sub_0009_invoke.o \
./src/model/sub_0009_model_data.o \
./src/model/sub_0009_tensors.o \
./src/model/sub_0010_command_stream.o \
./src/model/sub_0010_invoke.o \
./src/model/sub_0010_io_data.o \
./src/model/sub_0010_model_data.o \
./src/model/sub_0010_tensors.o \
./src/model/sub_0011_command_stream.o \
./src/model/sub_0011_invoke.o \
./src/model/sub_0011_model_data.o \
./src/model/sub_0011_tensors.o \
./src/model/sub_0012_command_stream.o \
./src/model/sub_0012_invoke.o \
./src/model/sub_0012_io_data.o \
./src/model/sub_0012_model_data.o \
./src/model/sub_0012_tensors.o \
./src/model/sub_0013_command_stream.o \
./src/model/sub_0013_invoke.o \
./src/model/sub_0013_model_data.o \
./src/model/sub_0013_tensors.o \
./src/model/sub_0014_command_stream.o \
./src/model/sub_0014_invoke.o \
./src/model/sub_0014_io_data.o \
./src/model/sub_0014_model_data.o \
./src/model/sub_0014_tensors.o \
./src/model/sub_0015_command_stream.o \
./src/model/sub_0015_invoke.o \
./src/model/sub_0015_model_data.o \
./src/model/sub_0015_tensors.o \
./src/model/sub_0016_command_stream.o \
./src/model/sub_0016_invoke.o \
./src/model/sub_0016_io_data.o \
./src/model/sub_0016_model_data.o \
./src/model/sub_0016_tensors.o \
./src/model/sub_0017_command_stream.o \
./src/model/sub_0017_invoke.o \
./src/model/sub_0017_model_data.o \
./src/model/sub_0017_tensors.o \
./src/model/sub_0018_command_stream.o \
./src/model/sub_0018_invoke.o \
./src/model/sub_0018_io_data.o \
./src/model/sub_0018_model_data.o \
./src/model/sub_0018_tensors.o \
./src/model/sub_0019_command_stream.o \
./src/model/sub_0019_invoke.o \
./src/model/sub_0019_model_data.o \
./src/model/sub_0019_tensors.o \
./src/model/sub_0020_command_stream.o \
./src/model/sub_0020_invoke.o \
./src/model/sub_0020_io_data.o \
./src/model/sub_0020_model_data.o \
./src/model/sub_0020_tensors.o \
./src/model/sub_0021_command_stream.o \
./src/model/sub_0021_invoke.o \
./src/model/sub_0021_model_data.o \
./src/model/sub_0021_tensors.o \
./src/model/sub_0022_command_stream.o \
./src/model/sub_0022_invoke.o \
./src/model/sub_0022_io_data.o \
./src/model/sub_0022_model_data.o \
./src/model/sub_0022_tensors.o \
./src/model/sub_0023_command_stream.o \
./src/model/sub_0023_invoke.o \
./src/model/sub_0023_model_data.o \
./src/model/sub_0023_tensors.o \
./src/model/sub_0024_command_stream.o \
./src/model/sub_0024_invoke.o \
./src/model/sub_0024_io_data.o \
./src/model/sub_0024_model_data.o \
./src/model/sub_0024_tensors.o \
./src/model/sub_0025_command_stream.o \
./src/model/sub_0025_invoke.o \
./src/model/sub_0025_model_data.o \
./src/model/sub_0025_tensors.o \
./src/model/sub_0026_command_stream.o \
./src/model/sub_0026_invoke.o \
./src/model/sub_0026_io_data.o \
./src/model/sub_0026_model_data.o \
./src/model/sub_0026_tensors.o \
./src/model/sub_0027_command_stream.o \
./src/model/sub_0027_invoke.o \
./src/model/sub_0027_model_data.o \
./src/model/sub_0027_tensors.o \
./src/model/sub_0028_command_stream.o \
./src/model/sub_0028_invoke.o \
./src/model/sub_0028_io_data.o \
./src/model/sub_0028_model_data.o \
./src/model/sub_0028_tensors.o \
./src/model/sub_0029_command_stream.o \
./src/model/sub_0029_invoke.o \
./src/model/sub_0029_model_data.o \
./src/model/sub_0029_tensors.o \
./src/model/sub_0030_command_stream.o \
./src/model/sub_0030_invoke.o \
./src/model/sub_0030_io_data.o \
./src/model/sub_0030_model_data.o \
./src/model/sub_0030_tensors.o \
./src/model/sub_0032_command_stream.o \
./src/model/sub_0032_invoke.o \
./src/model/sub_0032_io_data.o \
./src/model/sub_0032_model_data.o \
./src/model/sub_0032_tensors.o 

MAP += \
RA8P1_CAM_GLCDC_AI.map 


# Each subdirectory must supply rules for building sources it contributes
src/model/%.o: ../src/model/%.c
	@echo 'Building file: $<'
	$(file > $@.in,-mcpu=cortex-m85 -mthumb -mlittle-endian -mfloat-abi=hard -Os -ffunction-sections -fdata-sections -fno-strict-aliasing -fmessage-length=0 -funsigned-char -Wunused -Wuninitialized -Wall -Wextra -Wmissing-declarations -Wconversion -Wpointer-arith -Wshadow -Waggregate-return -Wno-parentheses-equality -Wfloat-equal -g3 -std=c99 -flax-vector-conversions -fshort-enums -fno-unroll-loops -I"D:\\Lab\\Lab_MCU\\Renesas_RA\\RA8P1_CAM_GLCDC_AI\\CameraTestProject\\e2studio\\src" -I"." -I"D:\\Lab\\Lab_MCU\\Renesas_RA\\RA8P1_CAM_GLCDC_AI\\CameraTestProject\\e2studio\\ra\\fsp\\inc" -I"D:\\Lab\\Lab_MCU\\Renesas_RA\\RA8P1_CAM_GLCDC_AI\\CameraTestProject\\e2studio\\ra\\fsp\\inc\\api" -I"D:\\Lab\\Lab_MCU\\Renesas_RA\\RA8P1_CAM_GLCDC_AI\\CameraTestProject\\e2studio\\ra\\fsp\\inc\\instances" -I"D:\\Lab\\Lab_MCU\\Renesas_RA\\RA8P1_CAM_GLCDC_AI\\CameraTestProject\\e2studio\\ra\\arm\\CMSIS_6\\CMSIS\\Core\\Include" -I"D:\\Lab\\Lab_MCU\\Renesas_RA\\RA8P1_CAM_GLCDC_AI\\CameraTestProject\\e2studio\\ra_gen" -I"D:\\Lab\\Lab_MCU\\Renesas_RA\\RA8P1_CAM_GLCDC_AI\\CameraTestProject\\e2studio\\ra_cfg\\fsp_cfg\\bsp" -I"D:\\Lab\\Lab_MCU\\Renesas_RA\\RA8P1_CAM_GLCDC_AI\\CameraTestProject\\e2studio\\ra_cfg\\fsp_cfg" -I"D:\\Lab\\Lab_MCU\\Renesas_RA\\RA8P1_CAM_GLCDC_AI\\CameraTestProject\\e2studio\\ra\\fsp\\src\\r_mipi_csi" -I"D:\\Lab\\Lab_MCU\\Renesas_RA\\RA8P1_CAM_GLCDC_AI\\CameraTestProject\\e2studio\\ra\\fsp\\src\\r_vin" -I"D:\\Lab\\Lab_MCU\\Renesas_RA\\RA8P1_CAM_GLCDC_AI\\CameraTestProject\\e2studio\\ra\\arm\\CMSIS-DSP\\PrivateInclude" -I"D:\\Lab\\Lab_MCU\\Renesas_RA\\RA8P1_CAM_GLCDC_AI\\CameraTestProject\\e2studio\\ra\\arm\\CMSIS-DSP\\Include" -I"D:\\Lab\\Lab_MCU\\Renesas_RA\\RA8P1_CAM_GLCDC_AI\\CameraTestProject\\e2studio\\ra\\fsp\\src\\rm_ethosu" -I"D:\\Lab\\Lab_MCU\\Renesas_RA\\RA8P1_CAM_GLCDC_AI\\CameraTestProject\\e2studio\\ra\\npu\\tflite-micro" -I"D:\\Lab\\Lab_MCU\\Renesas_RA\\RA8P1_CAM_GLCDC_AI\\CameraTestProject\\e2studio\\ra\\npu\\ruy" -I"D:\\Lab\\Lab_MCU\\Renesas_RA\\RA8P1_CAM_GLCDC_AI\\CameraTestProject\\e2studio\\ra\\npu\\gemmlowp" -I"D:\\Lab\\Lab_MCU\\Renesas_RA\\RA8P1_CAM_GLCDC_AI\\CameraTestProject\\e2studio\\ra\\npu\\ethos-u-core-driver\\include" -I"D:\\Lab\\Lab_MCU\\Renesas_RA\\RA8P1_CAM_GLCDC_AI\\CameraTestProject\\e2studio\\ra\\npu\\ethos-u-core-software\\lib\\layer_by_layer_profiler\\include" -I"D:\\Lab\\Lab_MCU\\Renesas_RA\\RA8P1_CAM_GLCDC_AI\\CameraTestProject\\e2studio\\ra\\npu\\ethos-u-core-software\\lib\\ethosu_monitor\\include" -I"D:\\Lab\\Lab_MCU\\Renesas_RA\\RA8P1_CAM_GLCDC_AI\\CameraTestProject\\e2studio\\ra\\npu\\ethos-u-core-software\\lib\\ethosu_profiler\\include" -I"D:\\Lab\\Lab_MCU\\Renesas_RA\\RA8P1_CAM_GLCDC_AI\\CameraTestProject\\e2studio\\ra\\npu\\ethos-u-core-software\\lib\\crc\\include" -I"D:\\Lab\\Lab_MCU\\Renesas_RA\\RA8P1_CAM_GLCDC_AI\\CameraTestProject\\e2studio\\ra\\npu\\ethos-u-core-software\\lib\\arm_profiler\\include" -I"D:\\Lab\\Lab_MCU\\Renesas_RA\\RA8P1_CAM_GLCDC_AI\\CameraTestProject\\e2studio\\ra\\arm\\CMSIS-View\\EventRecorder\\Include" -I"D:\\Lab\\Lab_MCU\\Renesas_RA\\RA8P1_CAM_GLCDC_AI\\CameraTestProject\\e2studio\\ra\\arm\\CMSIS-View\\EventRecorder\\Config" -I"D:\\Lab\\Lab_MCU\\Renesas_RA\\RA8P1_CAM_GLCDC_AI\\CameraTestProject\\e2studio\\ra\\npu\\flatbuffers\\include" -I"D:\\Lab\\Lab_MCU\\Renesas_RA\\RA8P1_CAM_GLCDC_AI\\CameraTestProject\\e2studio\\ra\\arm\\CMSIS-NN\\Include" -I"D:\\Lab\\Lab_MCU\\Renesas_RA\\RA8P1_CAM_GLCDC_AI\\CameraTestProject\\e2studio\\ra\\arm\\CMSIS-NN" -I"D:\\Lab\\Lab_MCU\\Renesas_RA\\RA8P1_CAM_GLCDC_AI\\CameraTestProject\\e2studio\\ra\\tes\\dave2d\\inc" -I"D:\\Lab\\Lab_MCU\\Renesas_RA\\RA8P1_CAM_GLCDC_AI\\CameraTestProject\\e2studio\\ra\\fsp\\src\\r_drw" -D_RENESAS_RA_ -D_RA_CORE=CPU0 -D_RA_ORDINAL=1 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -x c "$<" -c -o "$@")
	@clang --target=arm-none-eabi @"$@.in"

